name: Workflow 1

on:
  push:
    branches:
      # Use a wildcard to match branches starting with 'feature-'
      - "feature-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # this text must conflict with the one on feature-1 branch
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest

      - name: Validar resultado con errores
        if: ${{ failure() }}
        env:
          MENSAJE_ERROR: Una o varias pruebas fallaron
        run: echo "::set-output name=respuesta::${MENSAJE_ERROR}"
      - name: Validar resultado sin errores
        if: ${{ success() }}
        env:
          MENSAJE_EXITO: Todas las pruebas fueron exitosas
        run: echo "respuesta=${MENSAJE_EXITO}" >> $GITHUB_OUTPUT

      - name: Run coverage
        run: |
          coverage run -m unittest
          coverage report -m
