name: Automerge on pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - unlocked
      - labeled
      - unlabeled
      - edited
      - ready_for_review
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest

      - name: Run coverage
        run: |
          coverage run -m unittest
          coverage report -m

  automerge:
    name: Automerge
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_FORKS: "false"
          MERGE_REQUIRED_APPROVALS: 0
          MERGE_DELETE_BRANCH: "true"
